In [9]:
import numpy as np
X = np.array([
    [1.0,0.0,1.0],
    [0.0,2.2,2.0],
    [1.0,1.0,0.0]
]);

print("Input Embeddings (X):")
print(X)

np.random.seed(42)
d_model = X.shape[1]
d_k = 3
WQ = np.random.randn(d_model, d_k)
WK = np.random.randn(d_model, d_k)
WV = np.random.randn(d_model, d_k)

Q = X @ WQ
K = X @ WK
V = X @ WV

print("\nQuery (Q):")
print(Q)
print("\nKey (K):")
print(K)
print("\nValue (V):")
print(V)

scores = Q @ K.T
print("\nAttention Scores:")
print(scores)

scaled_scores = scores / np.sqrt(d_k)
print("\nScaled Scores:")
print(scaled_scores)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)


attention_weight = softmax(scaled_scores)
print("\nAttention Weight:")
print(attention_weight)


attention_output = attention_weight @ V
print("\nFinal Attention Output:")
print(attention_output)

Input Embeddings (X):
[[1.  0.  1. ]
 [0.  2.2 2. ]
 [1.  1.  0. ]]

Query (Q):
[[ 2.07592697  0.62917043  0.17821415]
 [ 6.50909132  1.01973203 -1.45405008]
 [ 2.01974401 -0.37241768  0.41355158]]

Key (K):
[[-0.01972749 -1.47624881 -0.15148242]
 [-0.59225806 -6.23487878 -3.16632457]
 [ 0.78452232 -2.37669794 -2.19064759]]

Value (V):
[[-1.4524068  -1.30138111  0.31465519]
 [-1.58547331  0.37040723 -5.43643316]
 [-1.13380038 -1.3447755   0.04090058]]

Attention Scores:
[[-0.99676123 -5.71656968 -0.25714143]
 [-1.41352318 -5.60897294  5.86824366]
 [ 0.44729089 -0.18366914  1.5637128 ]]

Scaled Scores:
[[-0.57548036 -3.30046304 -0.14846067]
 [-0.81609799 -3.23834204  3.38803206]
 [ 0.25824351 -0.10604143  0.90281   ]]

Attention Weight:
[[0.38487737 0.02522769 0.58989494]
 [0.01469485 0.00130376 0.98400139]
 [0.27778903 0.19297816 0.52923281]]

Final Attention Output:
[[-1.26781944 -1.28480389  0.00808207]
 [-1.13907112 -1.34190163  0.03778223]
 [-1.30946876 -1.00172821 -0.94005916]]
